### ISSUE TITLE
Switched hemispheres in GUI Electrode location?

### ISSUE THREAD

**Issue by seqasim** [Rolston-Lab/LeGUI#2]
Hi,

I've noticed, while using the GUI and drawing electrodes, that the hemispheres seem to be switched up on me. 
For example, I know that the selected electrode is in the left hemisphere:

<img width="440" alt="Screen Shot 2022-03-02 at 10 49 45 AM" src="https://user-images.githubusercontent.com/15975112/156405339-c63416ab-14ef-40ae-85bc-471641850da1.png">

However, the GUI seems to think it is in the right hemisphere:

<img width="362" alt="Screen Shot 2022-03-02 at 11 30 43 AM" src="https://user-images.githubusercontent.com/15975112/156405701-05c5f246-d991-4740-9cfa-e75228f08efa.png">

This has been the case in a couple of different subjects I have tried this with. 

I'm quite sure I determined the image orientations correctly in the first step, so the left-right axis orientation should be correct? 

I don't know if this actually matters, but wanted to make sure it's not indicative of an error in my process.

**Comment by tyler-davis** [comment]
I recently identified a bug in the software that is causing this problem. I will upload the fix soon!

**Comment by tyler-davis** [comment]
I just updated/committed a fix. The change was made to LeG_rotateImg2Standard. Please download the updated file and replace in your LeGUI installation folder. You will have to rerun those datasets with the flip error. If you are using the compiled software, I will incorporate this change in a new release soon!

**Comment by tyler-davis** [comment]
Let me know if this fix doesn't solve your problem. Thanks!

**Comment by tyler-davis** [comment]
I just published v1.2 of the software with a fix for this left/right flip issue.

**Comment by seqasim** [comment]
Hi, 

I am trying the new compiled and source versions (v1.2) and I am still getting the same error (see screenshot). The highlighted electrode should definitely be labeled as a right hemisphere electrode. 

<img width="1372" alt="Screen Shot 2022-03-22 at 2 09 00 PM" src="https://user-images.githubusercontent.com/15975112/159556144-76f1df7a-84c2-427c-aedf-ef194aeeafd0.png">

**Comment by tyler-davis** [comment]
The highlighted electrode is on the left side of the brain in the picture you are showing. The 2d image uses the radiological convention so the right is on the left and vice versa. In the 3D display, it looks like the electrode is on the left side. Does this answer your question?

**Comment by seqasim** [comment]
Not exactly - I know this is a right hemisphere electrode because it has microwires protruding from the tip that were only used on the right side. There is another 14-lead electrode terminating in the ACC (nearby in the 3d display) that was only used on the right (left is 12-lead). 

HOWEVER! 

I realized my mistake here. **I did not use the new flip left/right check box when verifying the orientation in Step 1. Doing so solved the problem!** I had not done this when trying v 1.2 the first time around. 

Thanks for your help and patience!

**Comment by JAQuent** [comment]
Reading this I think I might have a stupid question other this particular case, how do I know whether LeGUI guesses the right left/right orientation for the dicoms images? I have asymmetrice electrodes left & right so I can't really tell based on a specific electrode and I've just been send these dicoms images for CT and MRI with little extra information.

**Comment by tyler-davis** [comment]
I use a spm12 function to read the dicom images, so I’m not sure how the left/right orientation is determined. However, I haven't encountered any left/right issues when loading dicoms directly in LeGUI. I also added a popup message that appears if a possible left/right switch is needed. If this appears, just select the “flip left/right” checkbox in the ACPCGUI before closing. In the end, it’s always best to double check the left/right orientation using asymmetry in the electrode montage or known anatomical features.


On Jun 20, 2022, at 7:05 AM, Jörn Alexander Quent ***@***.***> wrote:

﻿

Reading this I think I might have a stupid question other this particular case, how do I know whether LeGUI guesses the right left/right orientation for the dicoms images? I have asymmetrice electrodes left & right so I can't really tell based on a specific electrode and I've just been send these dicoms images for CT and MRI with little extra information.

**Comment by tyler-davis** [comment]
The highlighted electrode is on the left side of the brain in the picture you are showing. The 2d image uses the radiological convention so the right is on the left and vice versa. In the 3D display, it looks like the electrode is on the left side. Does this answer your question?

Tyler

On Mar 22, 2022, at 1:02 PM, seqasim ***@***.***> wrote:

﻿

Hi,

I am trying the new compiled and source versions (v1.2) and I am still getting the same error (see screenshot). The highlighted electrode should definitely be labeled as a right hemisphere electrode.

[Screen Shot 2022-03-22 at 2 09 00 PM]<https://user-images.githubusercontent.com/15975112/159556144-76f1df7a-84c2-427c-aedf-ef194aeeafd0.png>
